### ISSUE TITLE
Restrict checkstyle

### ISSUE THREAD

**Issue by Glusk** [Glusk2/wse#24]
In https://github.com/Glusk2/wse/pull/7#issuecomment-361647901 it was suggested to review checkstyle rules. Decide what can and should be restricted.

**Comment by Glusk2** [comment]
Javadocs missing!

**Comment by Glusk** [comment]
Javadocs missing!

**Comment by Glusk** [comment]
See [this](https://stackoverflow.com/a/22556386/6367213) to get rid of unwanted annotation warnings in Eclipse.

**Comment by Glusk** [comment]
Will not document the code any further, hence there's no need to restrict checkstyle.
